# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts

[lua]
disabled = true

[package]
disabled = true

[fill]
symbol = '-'
style = 'bold green'


[gcloud]
disabled = true

