live_config_reload = true

# import = ["~/.config/alacritty/themes/themes/monokai.toml"]
# [colors.primary]
# background = "#2C2E33"
# foreground = "#f8f8f2"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0
#
# [[colors.indexed_colors]]
# color = "0xF8BD96"
# index = 16
#
# [[colors.indexed_colors]]
# color = "0xF5E0DC"
# index = 17
#
# [colors.bright]
# black = "0x988BA2"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"
#
# [colors.cursor]
# cursor = "0xF5E0DC"
# text = "0x1E1D2F"
#
# [colors.normal]
# black = "0x6E6C7E"
# blue = "0x96CDFB"
# cyan = "0x89DCEB"
# green = "0xABE9B3"
# magenta = "0xF5C2E7"
# red = "0xF28FAD"
# white = "0xD9E0EE"
# yellow = "0xFAE3B0"
#
# [colors.primary]
# background = "0x1E1D2F"
# foreground = "0xD9E0EE"
#
[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001n"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001f"
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001s"
key = "S"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001o"
key = "O"
mods = "Command"

[mouse]
hide_when_typing = true

[scrolling]
history = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["-l", "-c", "tmux attach || tmux new -A -s home"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
# opacity = 0.9999

[window.padding]
x = 4
y = 4
